name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  firebase_core: ^4.2.1
  intl: 0.19.0
  table_calendar: ^3.0.9
  image_picker: ^1.1.2
  file_picker: ^8.0.0
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  firebase_database: ^12.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets\IllustrationLogin.png
    - assets\IllustrationRegister.png
    - assets\logo.png
    - assets\User.png
    - assets\happy.png


