name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  firebase_core: ^4.2.1
  intl: 0.19.0
  table_calendar: ^3.0.9
<<<<<<< HEAD
  image_picker: ^1.1.2
  file_picker: ^8.0.0
=======
  flutter_localization: ^0.3.3
>>>>>>> 11aa680527d64057feedc6a6c104418d7dcf0c75

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
<<<<<<< HEAD
    - assets\IllustrationLogin.png
    - assets\IllustrationRegister.png
    - assets\logo.png
    - assets\User.png
    - assets\happy.png


=======
    - assets/IllustrationLogin.png
    - assets/IllustrationRegister.png
    - assets/logo.png
    - assets/User.png
>>>>>>> 11aa680527d64057feedc6a6c104418d7dcf0c75
